server:
  port: 8080
spring:
  servlet:
    multipart:
      max-request-size:10MB
      max-file-size=10MB
  datasource:
    url: jdbc:mysql://111.230.251.119:3306/imp
    username: imp
    password: imp
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.huse.trace.web.pojo
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
